#!/usr/bin/env python3

import pygame
from pygame.locals import *

class key_map:
    def __init__(self):
        self.K_BACKSPACE=['K_BACKSPACE',pygame.K_BACKSPACE]
        self.K_TAB=['K_TAB', pygame.K_TAB]
        self.K_CLEAR=['K_CLEAR', pygame.K_CLEAR]
        self.K_RETURN=['K_RETURN', pygame.K_RETURN]
        self.K_PAUSE=['K_PAUSE', pygame.K_PAUSE]
        self.K_ESCAPE=['K_ESCAPE', pygame.K_ESCAPE]
        self.K_SPACE=['K_SPACE', pygame.K_SPACE]
        self.K_EXCLAIM=['K_EXCLAIM', pygame.K_EXCLAIM]
        self.K_QUOTEDBL=['K_QUOTEDBL', pygame.K_QUOTEDBL]
        self.K_HASH=['K_HASH', pygame.K_HASH]
        self.K_DOLLAR=['K_DOLLAR', pygame.K_DOLLAR]
        self.K_AMPERSAND=['K_AMPERSAND', pygame.K_AMPERSAND]
        self.K_QUOTE=['K_QUOTE', pygame.K_QUOTE]
        self.K_LEFTPAREN=['K_LEFTPAREN', pygame.K_LEFTPAREN]
        self.K_RIGHTPAREN=['K_RIGHTPAREN', pygame.K_RIGHTPAREN]
        self.K_ASTERISK=['K_ASTERISK', pygame.K_ASTERISK]
        self.K_PLUS=['K_PLUS', pygame.K_PLUS]
        self.K_COMMA=['K_COMMA', pygame.K_COMMA]
        self.K_MINUS=['K_MINUS', pygame.K_MINUS]
        self.K_PERIOD=['K_PERIOD', pygame.K_PERIOD]
        self.K_SLASH=['K_SLASH', pygame.K_SLASH]
        self.K_0=['K_0', pygame.K_0]
        self.K_1=['K_1', pygame.K_1]
        self.K_2=['K_2', pygame.K_2]
        self.K_3=['K_3', pygame.K_3]
        self.K_4=['K_4', pygame.K_4]
        self.K_5=['K_5', pygame.K_5]
        self.K_6=['K_6', pygame.K_6]
        self.K_7=['K_7', pygame.K_7]
        self.K_8=['K_8', pygame.K_8]
        self.K_9=['K_9', pygame.K_9]
        self.K_COLON=['K_COLON', pygame.K_COLON]
        self.K_SEMICOLON=['K_SEMICOLON', pygame.K_SEMICOLON]
        self.K_LESS=['K_LESS', pygame.K_LESS]
        self.K_EQUALS=['K_EQUALS', pygame.K_EQUALS]
        self.K_GREATER=['K_GREATER', pygame.K_GREATER]
        self.K_QUESTION=['K_QUESTION', pygame.K_QUESTION]
        self.K_AT=['K_AT', pygame.K_AT]
        self.K_LEFTBRACKET=['K_LEFTBRACKET', pygame.K_LEFTBRACKET]
        self.K_BACKSLASH=['K_BACKSLASH', pygame.K_BACKSLASH]
        self.K_RIGHTBRACKET=['K_RIGHTBRACKET', pygame.K_RIGHTBRACKET]
        self.K_CARET=['K_CARET', pygame.K_CARET]
        self.K_UNDERSCORE=['K_UNDERSCORE', pygame.K_UNDERSCORE]
        self.K_BACKQUOTE=['K_BACKQUOTE', pygame.K_BACKQUOTE]
        self.K_a=['K_a', pygame.K_a]
        self.K_b=['K_b', pygame.K_b]
        self.K_c=['K_c', pygame.K_c]
        self.K_d=['K_d', pygame.K_d]
        self.K_e=['K_e', pygame.K_e]
        self.K_f=['K_f', pygame.K_f]
        self.K_g=['K_g', pygame.K_g]
        self.K_h=['K_h', pygame.K_h]
        self.K_i=['K_i', pygame.K_i]
        self.K_j=['K_j', pygame.K_j]
        self.K_k=['K_k', pygame.K_k]
        self.K_l=['K_l', pygame.K_l]
        self.K_m=['K_m', pygame.K_m]
        self.K_n=['K_n', pygame.K_n]
        self.K_o=['K_o', pygame.K_o]
        self.K_p=['K_p', pygame.K_p]
        self.K_q=['K_q', pygame.K_q]
        self.K_r=['K_r', pygame.K_r]
        self.K_s=['K_s', pygame.K_s]
        self.K_t=['K_t', pygame.K_t]
        self.K_u=['K_u', pygame.K_u]
        self.K_v=['K_v', pygame.K_v]
        self.K_w=['K_w', pygame.K_w]
        self.K_x=['K_x', pygame.K_x]
        self.K_y=['K_y', pygame.K_y]
        self.K_z=['K_z', pygame.K_z]
        self.K_DELETE=['K_DELETE', pygame.K_DELETE]
        self.K_KP0=['K_KP0', pygame.K_KP0]
        self.K_KP1=['K_KP1', pygame.K_KP1]
        self.K_KP2=['K_KP2', pygame.K_KP2]
        self.K_KP3=['K_KP3', pygame.K_KP3]
        self.K_KP4=['K_KP4', pygame.K_KP4]
        self.K_KP5=['K_KP5', pygame.K_KP5]
        self.K_KP6=['K_KP6', pygame.K_KP6]
        self.K_KP7=['K_KP7', pygame.K_KP7]
        self.K_KP8=['K_KP8', pygame.K_KP8]
        self.K_KP9=['K_KP9', pygame.K_KP9]
        self.K_KP_PERIOD=['K_KP_PERIOD', pygame.K_KP_PERIOD]
        self.K_KP_DIVIDE=['K_KP_DIVIDE', pygame.K_KP_DIVIDE]
        self.K_KP_MULTIPLY=['K_KP_MULTIPLY', pygame.K_KP_MULTIPLY]
        self.K_KP_MINUS=['K_KP_MINUS', pygame.K_KP_MINUS]
        self.K_KP_PLUS=['K_KP_PLUS', pygame.K_KP_PLUS]
        self.K_KP_ENTER=['K_KP_ENTER', pygame.K_KP_ENTER]
        self.K_KP_EQUALS=['K_KP_EQUALS', pygame.K_KP_EQUALS]
        self.K_UP=['K_UP', pygame.K_UP]
        self.K_DOWN=['K_DOWN', pygame.K_DOWN]
        self.K_RIGHT=['K_RIGHT', pygame.K_RIGHT]
        self.K_LEFT=['K_LEFT', pygame.K_LEFT]
        self.K_INSERT=['K_INSERT', pygame.K_INSERT]
        self.K_HOME=['K_HOME', pygame.K_HOME]
        self.K_END=['K_END', pygame.K_END]
        self.K_PAGEUP=['K_PAGEUP', pygame.K_PAGEUP]
        self.K_PAGEDOWN=['K_PAGEDOWN', pygame.K_PAGEDOWN]
        self.K_F1=['K_F1', pygame.K_F1]
        self.K_F2=['K_F2', pygame.K_F2]
        self.K_F3=['K_F3', pygame.K_F3]
        self.K_F4=['K_F4', pygame.K_F4]
        self.K_F5=['K_F5', pygame.K_F5]
        self.K_F6=['K_F6', pygame.K_F6]
        self.K_F7=['K_F7', pygame.K_F7]
        self.K_F8=['K_F8', pygame.K_F8]
        self.K_F9=['K_F9', pygame.K_F9]
        self.K_F10=['K_F10', pygame.K_F10]
        self.K_F11=['K_F11', pygame.K_F11]
        self.K_F12=['K_F12', pygame.K_F12]  
        self.K_F13=['K_F13', pygame.K_F13]
        self.K_F14=['K_F14', pygame.K_F14]
        self.K_F15=['K_F15', pygame.K_F15]
        self.K_NUMLOCK=['K_NUMLOCK', pygame.K_NUMLOCK]
        self.K_CAPSLOCK=['K_CAPSLOCK', pygame.K_CAPSLOCK]
        self.K_SCROLLOCK=['K_SCROLLOCK', pygame.K_SCROLLOCK]
        self.K_RSHIFT=['K_RSHIFT', pygame.K_RSHIFT]
        self.K_LSHIFT=['K_LSHIFT', pygame.K_LSHIFT]
        self.K_RCTRL=['K_RCTRL', pygame.K_RCTRL]
        self.K_LCTRL=['K_LCTRL', pygame.K_LCTRL]
        self.K_RALT=['K_RALT', pygame.K_RALT]  
        self.K_LALT=['K_LALT', pygame.K_LALT]
        self.K_RMETA=['K_RMETA', pygame.K_RMETA]
        self.K_LMETA=['K_LMETA', pygame.K_LMETA]
        self.K_LSUPER=['K_LSUPER', pygame.K_LSUPER]
        self.K_RSUPER=['K_RSUPER', pygame.K_RSUPER]
        self.K_MODE=['K_MODE', pygame.K_MODE]
        self.K_HELP=['K_HELP', pygame.K_HELP]
        self.K_PRINT=['K_PRINT', pygame.K_PRINT]
        self.K_SYSREQ=['K_SYSREQ', pygame.K_SYSREQ]
        self.K_BREAK=['K_BREAK', pygame.K_BREAK]
        self.K_MENU=['K_MENU', pygame.K_MENU]   
        self.K_POWER=['K_POWER', pygame.K_POWER]
        self.K_EURO=['K_EURO', pygame.K_EURO]   
    def find_key(self, key_name):
        key_maps=dir(self)
        for key in key_maps:
            print('test')
            # print(getattr(pygame, key[0]))
            print(key_name)
            print('test')
            
            if getattr(pygame, key[0]) == key_name:
                print(key[1])
                return key[1]
            # else:
            #     print("error key not found")